import { sql } from "drizzle-orm";
import { integer, sqliteTable, text } from "drizzle-orm/sqlite-core";
import { primaryKeyAutoGenerated } from "./common";

export const productTable = sqliteTable("product", {
  id: primaryKeyAutoGenerated(),
  name: text("name").notNull(),
  imageUrl: text("imageUrl").notNull(),
  price: integer("price").notNull(),
  category: text("category").notNull().default("Unknown"),
  createdAt: text("createdAt")
    .notNull()
    .default(sql`CURRENT_TIMESTAMP`),
});
